### ISSUE TITLE
Permanent "Authentication failure" when locking screen

### ISSUE THREAD

**Issue by SoloRobo** [pop-os/cosmic-greeter#126]
Fedora 40
cosmic-greeter 0.1.0~^20240906git55c02cd

Locking the screen, I am unable to log back in as I am not presented with a field to enter my password, only the phrase "Authentication failure".

**Comment by hgaiser** [comment]
Same here, plus these messages in journalctl:

```
Sep 09 12:38:13 laptop /usr/lib/gdm-wayland-session[52593]: 2024-09-09T10:38:13.904717Z  WARN cosmic-greeter: cosmic_session: [2024-09-09T10:38:13Z WARN  cosmic_greeter::locker] authentication error: Authentication failure
Sep 09 12:38:13 laptop cosmic-greeter[52707]: pam_warn(cosmic-greeter:auth): function=[pam_sm_authenticate] flags=0 service=[cosmic-greeter] terminal=[<unknown>] user=[hgaiser] ruser=[<unknown>] rhost=[<unknown>]
Sep 09 12:38:13 laptop cosmic-session[52593]: [2024-09-09T10:38:13Z WARN  cosmic_greeter::locker] authentication error: Authentication failure
```

**Comment by chdalski** [comment]
For Fedora 40 it seems like the pam configuration for cosmic-greeter is missing.

**Comment by mmstick** [comment]
Make sure to report packaging issues to the Fedora team

**Comment by hgaiser** [comment]
> Make sure to report packaging issues to the Fedora team

For what it's worth, my issue is on Arch Linux.

**Comment by mmstick** [comment]
They probably aren't packaging the PAM config either

**Comment by hgaiser** [comment]
> They probably aren't packaging the PAM config either

Alright, thanks for the info. I see it is a relatively new addition (3 days ago), so you are probably correct. I will check it out later.

**Comment by hgaiser** [comment]
I tried copying `cosmic-greeter.pam` to `/etc/pam.d/cosmic-greeter`, then I get the following error:

```
Sep 09 14:47:39 laptop /usr/lib/gdm-wayland-session[138214]: 2024-09-09T12:47:39.269328Z  WARN cosmic-greeter: cosmic_session: [2024-09-09T12:47:39Z WARN  cosmic_greeter::locker] authentication error: Permission denied
Sep 09 14:47:39 laptop cosmic-session[138214]: [2024-09-09T12:47:39Z WARN  cosmic_greeter::locker] authentication error: Permission denied
Sep 09 14:47:39 laptop cosmic-greeter[138469]: gkr-pam: no password is available for user
```

I'm probably missing something, I am not familiar with these parts. I will report my issue on the AUR :+1:

**Comment by SoloRobo** [comment]
FYI I reported the Fedora issue to their Matrix channel, linking it back to this. goto 10.

**Comment by ryanabx** [comment]
On the fedora end, we are releasing a fix in https://pagure.io/fork/ryanabx/fedora-cosmic/cosmic-packaging/c/c750f1ba5822c89594d66169344bbb7ef472ebe9

**Comment by SoloRobo** [comment]
> On the fedora end, we are releasing a fix in https://pagure.io/fork/ryanabx/fedora-cosmic/cosmic-packaging/c/c750f1ba5822c89594d66169344bbb7ef472ebe9

Looks like its all built, did a dnf reinstall on the assumption the build number hadn't forced it through and still seeing the issue, what am I missing?

**Comment by ryanabx** [comment]
> did a dnf reinstall on the assumption the build number hadn't forced it through

Not sure what that means, sorry :/

But definitely `dnf upgrade` or `dnf distro-sync` should work to upgrade it. From there reboot and see if the file `/etc/pam.d/cosmic-greeter` exists

**Comment by SoloRobo** [comment]
Tried dnf upgrade and dnf distro-sync but that was after my dnf reinstall so maybe I broke by doing that?

This is what I have in pam.d

``` chfn
chsh
config-util
cups
fingerprint-auth
gdm-autologin
gdm-fingerprint
gdm-launch-environment
gdm-password
gdm-smartcard
greetd
greetd-greeter
login
other
passwd
password-auth
postlogin
ppp
remote
runuser
runuser-l
smartcard-auth
sshd
sssd-shadowutils
su
sudo
sudo-i
su-l
system-auth
vlock
vmtoolsd
xserver
```

**Comment by chdalski** [comment]
For `Fedora 40` I've copied /etc/pam.d/greetd to /etc/pam.d/cosmic-greeter.

This seems to work for now - even though I don't know if it's the expected configuration.

The file looks like:
```ini
#%PAM-1.0
auth       substack    system-auth
-auth       optional    pam_gnome_keyring.so
-auth       optional    pam_kwallet5.so
-auth       optional    pam_kwallet.so
auth       include     postlogin

account    required    pam_sepermit.so
account    required    pam_nologin.so
account    include     system-auth

password   include     system-auth

session    required    pam_selinux.so close
session    required    pam_loginuid.so
session    required    pam_selinux.so open
session    optional    pam_keyinit.so force revoke
session    required    pam_namespace.so
session    include     system-auth
-session    optional    pam_gnome_keyring.so auto_start
-session    optional    pam_kwallet5.so auto_start
-session    optional    pam_kwallet.so auto_start
session    include     postlogin
```

**Comment by Department-stack** [comment]
I was about to report this exact issue

**Comment by russ-dm** [comment]
Getting the same PAM failure in Arch.

```
Sep 11 14:47:44 archie systemd[1]: Failed to start COSMIC Greeter.
Sep 11 14:47:44 archie systemd[1]: cosmic-greeter.service: Failed with result 'start-limit-hit'.
Sep 11 14:47:44 archie systemd[1]: cosmic-greeter.service: Start request repeated too quickly.
Sep 11 14:47:44 archie systemd[1]: cosmic-greeter.service: Scheduled restart job, restart count>
Sep 11 14:47:43 archie systemd[1]: cosmic-greeter.service: Deactivated successfully.
Sep 11 14:47:43 archie greetd[46605]: error: PAM 'cosmic-greeter' service missing
Sep 11 14:47:43 archie greetd[46605]: config: Config { file: ConfigFile { terminal: ConfigTermi>
Sep 11 14:47:43 archie systemd[1]: Started COSMIC Greeter.
```

**Comment by abishekmuthian** [comment]
> For `Fedora 40` I've copied /etc/pam.d/greetd to /etc/pam.d/cosmic-greeter.
> 
> This seems to work for now - even though I don't know if it's the expected configuration.
> 


Thank you, this works.

**Comment by otaviobrum** [comment]
From what I understand @SoloRobo  is installing the same broken package and the package mentioned by @ryanabx  is not yet in the repository. My question now is: whoever uses the temporary solution proposed by @chdalski  will need to delete the contents of /etc/pam.d/cosmic-greeter or will the package overwrite it and everything will be correct @ryanabx ?

**Comment by thekarananand** [comment]
![IMG_20240914_214024.jpg](https://github.com/user-attachments/assets/a7621e2d-06f0-4e7e-b8bf-94f6b088268c)

On Fedora, after `sudo dnf update`, followed by a restart. What to do ?

**Comment by otaviobrum** [comment]
> ![IMG_20240914_214024.jpg](https://private-user-images.githubusercontent.com/68910143/367528413-a7621e2d-06f0-4e7e-b8bf-94f6b088268c.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYzMzE2NDIsIm5iZiI6MTcyNjMzMTM0MiwicGF0aCI6Ii82ODkxMDE0My8zNjc1Mjg0MTMtYTc2MjFlMmQtMDZmMC00ZTdlLWI4YmYtOTRmNmIwODgyNjhjLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE0VDE2MjkwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhNmQyN2M1ODQ1MGZlMjhmZTBlMzZjNjdlYjkxNGIxZDhhNzBhODMwMzRkOWFhZDI5ZGQ2OTNkNTQ0NDM1OGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9C21L1PDMGn1LXVsFv6R4enAezD8VrXGUwYlppKk7cE)
> 
> On Fedora, after `sudo dnf update`, followed by a restart. What to do ?

CTRL+ALT+F2 to login on the virtual terminal and sudo su - to login as root and finally cp /etc/pam.d/greetd  /etc/pam.d/cosmic-greeter &&  reboot

**Comment by ryanabx** [comment]
We're still trying to figure out the issue. This is the first time I've installed a file in an rpm and it didn't show up for end users. It's really odd. It also doesn't seem to matter whether we install it in `/etc/pam.d` or `/usr/lib/pam.d`, it doesn't show up either way.

**Comment by nevdelap** [comment]
I can confirm that this works in Arch as a workaround

```
/etc/pam.d > sudo ln -s greetd cosmic-greeter
```

**Comment by rsulli55** [comment]
I copied `/etc/pam.d/greetd`  `/etc/pam.d/cosmic-greeter` and the lock screen is now allowing me to log in again, but `coscmic_greeter` is still constantly producing warnings.
```bash
$ journalctl -r  | grep cosmic
... <many more copies>
cosmic-session[4527]: [2024-09-15T17:08:59Z WARN  cosmic_greeter::locker] authentication error: Authentication failure
cosmic-session[4527]: [2024-09-15T17:08:59Z WARN  cosmic_greeter::locker] authentication error: Authentication failure
cosmic-session[4527]: [2024-09-15T17:08:59Z WARN  cosmic_greeter::locker] authentication error: Authentication failure
cosmic-session[4527]: [2024-09-15T17:08:58Z WARN  cosmic_greeter::locker] authentication error: Authentication failure
cosmic-session[4527]: [2024-09-15T17:08:58Z WARN  cosmic_greeter::locker] authentication error: Authentication failure
... <many more copies>
```

**Comment by SoloRobo** [comment]
Fedora 40 & 41 COPR packages are all fixed

**Comment by aharish** [comment]
If anyone is using the main `cosmic` packages on Arch (not AUR), the alpha 2.1 update causes `cosmic-greeter` to not start, leaving you with a broken system. Jumping over to another terminal running `sudo ln -s greetd cosmic-greeter` should fix the issue. Make sure to restart `cosmic-greeter` once you symlink the file.

**Comment by jackpot51** [comment]
Arch Linux packaging bug: https://gitlab.archlinux.org/archlinux/packaging/packages/cosmic-greeter/-/issues/4

**Comment by alucryd** [comment]
> Arch Linux packaging bug: https://gitlab.archlinux.org/archlinux/packaging/packages/cosmic-greeter/-/issues/4

Reverted the PAM changes while we work on a solution for the keyring. The supplied PAM configuration had issues on Arch.

**Comment by jackpot51** [comment]
Thank you @alucryd!
