### ISSUE TITLE
cosmic-greeter.service Fails to start on boot.

### ISSUE THREAD

**Issue by Raktbastr** [pop-os/cosmic-greeter#133]
cosmic-greeter.service Fails to start on boot, cosmic-greeter-daemon.service does not however.

When I do log in and start using cosmic the lock screen also wont respond to input and says "Authentication Failed" In the log in area. I believe these problems are related. 

System Details:

OS: Arch Linux
Kernel: Linux 6.10.10-arch1-1
Cosmic Version: Latest on Arch repos

I also tried editing the time before it restarts, did not fix it.
It is also only disabled because I needed to use SDDM instead to actually get into cosmic. I still get the same issue.

`systemctl status cosmic-greeter` returns this:

```
× cosmic-greeter.service - COSMIC Greeter
     Loaded: loaded (/usr/lib/systemd/system/cosmic-gr
eeter.service; disabled; preset: disabled)
     Active: failed (Result: start-limit-hit) since Thu 2024-09-26 17:16:41 CDT; 8min ago
   Duration: 59ms
 Invocation: c2c73f65de224044808a148b3fec81d2
   Main PID: 815 (code=exited, status=0/SUCCESS)

Sep 26 17:16:41 overlord systemd[1]: cosmic-greeter.service: Scheduled restart job, restart counter is at 4.
Sep 26 17:16:41 overlord systemd[1]: cosmic-greeter.service: Start request repeated
 too quickly.
Sep 26 17:16:41 overlord systemd[1]: cosmic-greeter.service: Failed with result 'st
art-limit-hit'.
Sep 26 17:16:41 overlord systemd[1]: Failed to start COSMIC Greeter.
```

**Comment by jackpot51** [comment]
I believe the packaging for Arch Linux is missing the cosmic-greeter PAM service and this should be submitted there.

**Comment by jackpot51** [comment]
Arch Linux packaging bug: https://gitlab.archlinux.org/archlinux/packaging/packages/cosmic-greeter/-/issues/4

**Comment by Raktbastr** [comment]
Latest update fixes issue
