### ISSUE TITLE
bug: password field is not focused on screen wake

### ISSUE THREAD

**Issue by edfloreshz** [pop-os/cosmic-greeter#145]
Sometimes after waking the screen I have to manually click on the password field to focus it. I haven't figured out a way to replicate this behavior.

I have noticed however, that you can click `Tab` you can focus either the buttons, the password field or nothing at all, I believe that the latter is capturing the focus and that's what causes the password field to be unfocused.

## Steps to reproduce
1. `Super +  Esc` to show the greeter.
2. Click on the password field if not focused.
3. Click `Tab` and see the focus disappear.

The focus should go to the buttons and back to the password field, there's something else capturing the focus.

**Comment by leviport** [comment]
I think this is a duplicate of https://github.com/pop-os/cosmic-greeter/issues/135?

**Comment by edfloreshz** [comment]
Right, I'll close this and comment on #135
