### ISSUE TITLE
[BUG] [SECURITY] Cosmic greeter crash when displays disconnect and unlocks user's desktop without auth

### ISSUE THREAD

**Issue by gmpinder** [pop-os/cosmic-greeter#151]
version: `cosmic-greeter-1.0.0~alpha.2^git20241014.7366808-1.fc40.x86_64`
os: `Bazzite 40 (FROM Fedora Kinoite)`
display manager: SDDM

I've got my system setup with a KVM that disconnects my monitors from the PC when switching. I normally will lock my system (`Super+Esc`) before switching, but now when I switch back the greeter crashes and drops me into a fresh desktop session without making me login.

**Comment by Drakulix** [comment]
That doesn't sound like a cosmic-greeter crash (which wouldn't leave you with an open session), but a compositor crash (which indeed the "locked" state wouldn't survive, we need to fix that). Do you have a log for that crash? (`journalctl --user _COMM=cosmic-comp`)

**Comment by gmpinder** [comment]
Makes sense. Here's what I've got
[comic-comp-journal.log](https://github.com/user-attachments/files/17576160/comic-comp-journal.log)

**Comment by ids1024** [comment]
Is this consistently reproducible? I don't seem to see this, though maybe I'm not testing the exact same situation.

It would be clearer to see what's going on in a debug build that produces a more complete backtrace.

But if https://github.com/pop-os/cosmic-comp/blob/eb64fdaf8fe4f5e6957a35e74004b183acc905c8/src/shell/mod.rs#L974 is failing, `.active()` is being called before `.add_output()` has added the output? Or after the output has been removed.

**Comment by gmpinder** [comment]
It's very consistent for me, like every time I perform the action of locking, switching the KVM, and switching back. I have 2 monitors plugged into the KVM. Both are 2560x1440. One goes up to 144Hz and the other up to 60Hz.

**Comment by gmpinder** [comment]
> It would be clearer to see what's going on in a debug build that produces a more complete backtrace.

I'm running the COPR build of cosmic on a Fedora Atomic image. Is there an easy way for me to run a debug build?

**Comment by LavaHeron** [comment]
I found a very similar bug, maybe that helps. [pop-os/cosmic-epoch#1214](https://github.com/pop-os/cosmic-epoch/issues/1214)

**Comment by gmpinder** [comment]
Awesome! I see you guys fixed the lock issue and it does prevent me from getting into my session without a password. Now I just need to get some debug logs for the compositor crashing issue. I'll go ahead and close this issue and open a new one when I get that information.
