### ISSUE TITLE
Can no longer launch Wayland Gnome sessions. 

### ISSUE THREAD

**Issue by XV-02** [pop-os/cosmic-greeter#18]
I'm uncertain when this began to be an issue, but I am finding I can no longer launch Gnome sessions using Wayland. I can launch Xorg Gnome sessions intermittently - though something in how those sessions launch is breaking Pop extensions for Gnome - but when ever I attempt to launch a Wayland session of Gnome, the screen goes black, as though it is launching a session, and immediately returns me to the `greeter` login prompt.

**Comment by jokeyrhyme** [comment]
I can reproduce this, although as I've never been able to get cosmic-greeter to launch GNOME successfully during the life of this project, it's possible my root cause is different (as the original report seems related to a recent-ish change)

**Comment by jokeyrhyme** [comment]
@XV-02 I don't suppose you've tried building a commit from a few months ago (or whenever you last remember it working) and seeing if you can `git bisect` your way to the first commit where it stopped working?

**Comment by XV-02** [comment]
Having looked at this recently, I have noted that the issues seem to crop up after 5d0999df8312e56bebf998cd2e359e3b1269731d or 8d91f3c4ea85c68102d5ca578e3a3d0e7d5d2ab2 though I'm unsure which. 

Beyond that, I don't have issues with launching KDE Plasma as a wayland session, nor Weston. Launching Gnome as an X11 session still works - though it can take a few attempts. 

I'm fairly certain it isn't Pop specific. Building and installing cosmic on base Ubuntu has the same issues.

The first of these is a full log for a boot with two attempts to log in to Ubuntu with Gnome-Wayland before shutting down. The second is the same log with most of the initial boot-time kernel stuff and the shutdown stuff culled, as well as a number of bluetooth errors which didn't seem relevant, but were distracting. 
[LogsFull.log](https://github.com/pop-os/cosmic-greeter/files/15069025/LogsFull.log)
[LogsExcerpt.log](https://github.com/pop-os/cosmic-greeter/files/15069026/LogsExcerpt.log)
