### ISSUE TITLE
Add Reboot and Shutdown

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/cosmic-greeter#39]
With confirmation dialog

https://www.figma.com/file/SkAtS5qlVOGQC0n895AHzX/Design-System-(WIP)?type=design&node-id=8235-11383&mode=design&t=Uy0g6aDVHcc7FAsz-0

**Comment by jackpot51** [comment]
Implemented in bfe8d8506b96ec5f14118154fa46a78b703c1662
