### ISSUE TITLE
Lock screen often fails to activate during a session

### ISSUE THREAD

**Issue by WatchMkr** [pop-os/cosmic-greeter#72]
> In case it's helpful, I've noticed that lock screen working or not working seems to be consistent throughout any single cosmic session. If I start a session and it's working, it'll keep working until I logout/restart/etc.

**Comment by curiousercreative** [comment]
The above quote is from this chat: https://chat.pop-os.org/pop-os/pl/1mekfar1htgomfgoa8jh5ycu4c

**Comment by hgaiser** [comment]
I have a possible fix for this in https://github.com/pop-os/cosmic-applets/pull/533.

**Comment by WatchMkr** [comment]
I'm still experiencing this one.

**Comment by wash2** [comment]
I believe https://github.com/pop-os/cosmic-greeter/pull/81 will fix this issue

**Comment by curiousercreative** [comment]
FWIW, I just reproduced this bug again with the latest from dev repos.
