### ISSUE TITLE
Show Password don't work

### ISSUE THREAD

**Issue by LinuxBoy-96** [pop-os/cosmic-greeter#91]
The Show Passwork Icon, right at the password entry area, does not actually show the password, It does nothing.

**Comment by kekkoudesu** [comment]
Also seeing this on Arch Linux with `cosmic-greeter 1.0.0.alpha.1-2`

**Comment by TornaxO7** [comment]
AFAIK `show password` doesn't work for the greeter currently but the locker works.

**Comment by TornaxO7** [comment]
Can anyone try my branch? https://github.com/TornaxO7/cosmic-greeter/tree/fix-show-password-for-greeter

I can't test it out on my machine because cosmic doesn't load for me at all if I try to run it on my machine.

**Comment by git-f0x** [comment]
The branch seems to be working as expected on my end, and fixes this issue.

**Comment by TornaxO7** [comment]
![peepoAwesome](https://github.com/user-attachments/assets/0f58af33-ab9e-4df2-b58c-7f071fb5bf16)
